name: Azure
version: ${project.version}
main: me.grabsky.azure.Azure
api-version: 1.17
authors: [Grabsky]
depend: [Indigo]
softdepend: [Vault]
permissions:
  azure.command.azure.*:
    children:
      azure.command.azure: false
      azure.command.azure.reload: false

  azure.command.teleport.*:
    children:
      azure.command.teleport: false
      azure.command.teleport.others: false

  azure.command.teleporthere.*:
    children:
      azure.command.teleporthere: false

  azure.command.teleportlocation.*:
    children:
      azure.command.teleportlocation: false

  azure.command.rename.*:
    children:
      azure.command.rename: false

  azure.command.lore.*:
    children:
      azure.command.lore: false
      azure.command.lore.add: false
      azure.command.lore.set: false
      azure.command.lore.remove: false
      azure.command.lore.clear: false

  azure.command.enchant.*:
    children:
      azure.command.enchant: false
      azure.command.enchant.add: false
      azure.command.enchant.remove: false

  azure.command.skull.*:
    children:
      azure.command.skull: false

  azure.command.home.*:
    children:
      azure.command.home: false

  azure.command.sethome.*:
    children:
      azure.command.sethome: false

  azure.command.delhome.*:
    children:
      azure.command.delhome: false

  azure.command.heal.*:
    children:
      azure.command.heal: false

  azure.command.feed.*:
    children:
      azure.command.feed: false

  azure.command.invsee.*:
    children:
      azure.command.invsee: false

  azure.command.enderchest.*:
    children:
      azure.command.enderchest: false
      azure.command.enderchest.others: false

  azure.command.speed.*:
    children:
      azure.command.speed: false
