name: Gradle CI

on:
  push:
    branches: ["main"]

# Permissions
permissions:
  contents: read

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    # Permissions
    permissions:
      packages: write
    steps:
      # Checkout
      - uses: actions/checkout@v3
      # Configure Java 21
      - name: JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      # Build and Publish
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean shadowJar publish --no-daemon
        env:
          # GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: plugin/build/libs
  create_release:
    runs-on: ubuntu-latest
    # We need to wait for the previous job to finish.
    needs: "build_and_publish"
    # Permissions
    permissions:
      contents: write
    steps:
      # Checkout
      - uses: actions/checkout@v3
      # Configure Java 21
      - name: JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      # Configure Gradle
      - name: Configure Gradle
        uses: gradle/gradle-build-action@v2
      # Expose Release Name
      - name: Expose Release Name
        run: echo "PROJECT_RELEASE_NAME=$( ./gradlew release --quiet --no-rebuild )" >> $GITHUB_ENV
      # Expose Tag
      - name: Expose Tag
        run: echo "PROJECT_TAG=$( ./gradlew tag --quiet --no-rebuild )" >> $GITHUB_ENV
      # Release
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.PROJECT_RELEASE_NAME }}"
          tag: "${{ env.PROJECT_TAG }}"
