name: Gradle CI + Publish

on:
  push:
    branches: ["main", "dev/build-environment"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checking out
      - uses: actions/checkout@v3
      # Setting up Java 17
      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      # Building
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean shadowJar
        env:
          # GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Uploading artifact(s)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: plugin/build/libs
      # Publishing
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          # GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
