name: Gradle Assemble

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checking out
      - uses: actions/checkout@v3
      # Setting up Java 17
      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # Building
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean shadowJar
      # Uploading artifact(s)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs
      # Publishing
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          # GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Cloud Repository
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_SECRET: ${{ secrets.REPO_SECRET }}
